### ISSUE TITLE
Some notes on the code

### ISSUE THREAD

**Issue by kuraga** [lazyscribe/lazyscribe#28]
Good day!

Thanks for your project!

I have tried to use the package. Some notes on the code:

_p. 1._

Don't see the `Code Reference` pages on https://lazyscribe.readthedocs.io/en/latest/. (There doc comments in the code though.)

_p. 2._

The `/.DS_Store` file can be ignored via the `/.gitignore`.

_p. 3._

Move `/tutorials` to `/docs/tutorials`?

_p. 4._

The [the `Create a basic project` how-to](https://lazyscribe.readthedocs.io/en/latest/how-to/basic.html) and [the `Log non-global metrics` how-to](https://lazyscribe.readthedocs.io/en/latest/how-to/tests.html) don't say to `.save` on `project`. Is it correct?

_p. 5._

The `Project.to_tabular`'s docs [don't mention](https://github.com/lazyscribe/lazyscribe/blob/9c110cc32a24ecbf9ac5a836c2617dba253def90/lazyscribe/project.py#L301-L325) the `parameters` items in the `global project list` return value. But [there are they](https://github.com/lazyscribe/lazyscribe/blob/9c110cc32a24ecbf9ac5a836c2617dba253def90/lazyscribe/project.py#L364-L368).

_p. 6._

How do I log _per-epoch_ metrics, etc.?

Sincerely.

**Comment by kuraga** [comment]
@ak-gupta ,

5. Using neural networks, we have metric value(s) at each epoch.

**Comment by ak-gupta** [comment]
Tests are nested within experiments. They're designed to allow you to associate metrics with an experiment without relying on nomenclature to distinguish a global performance metric, for example, from one that applies to a subpopulation.

**Comment by kuraga** [comment]
Then yes, I should use `name=f'epoch_${epoch}'` for a test.

**Comment by ak-gupta** [comment]
Please let us know if that works well for you!

**Comment by kuraga** [comment]
Ok, the new thoughts.

5. OK, I've used it for the neural networks training. Everything is as expected now.
    But could we add the `properties: Dict[str, Any]` argument to the `Experiment` and `Test` constructors? That "properties"/"attribites" being saved, they could help to filter the experiments/tests.
6. IMHO https://github.com/lazyscribe/lazyscribe/blob/9c110cc32a24ecbf9ac5a836c2617dba253def90/lazyscribe/project.py#L334-L338 should be prefixed with `experiment_`.
7. IMHO `str(experiment)` and `str(test)` should output much less information. There is the `repr` for that.
  (Note: don't see in code why that isn't such.)
8. Maybe we may mention in the tutorials that `.experiments` and `.tests` are just plain `List`s hence `.append`ing: a) saves the order, b) saves the link instead of a copy (hence we can modify the experiment/test until `project.save()`).
9. Add the `.to_dict()` description to the `Represent the project as a table` tutorial (and rename the latter).
10. "Storage drivers" other than JSON?

Thanks!

P.S. The Artifacts haven't been seen yet. All thoughts about experiments and tests can be potentially used for artifacts.

**Comment by ak-gupta** [comment]
5. I'd love to know more about the "properties". What sort of information are you looking to associate with an experiment that can't/shouldn't be stored via `parameters`?
6. Ah I see, yep. Instead of the user potentially interpreting those values as the "test name", `experiment_name` is more explicit.
7. Good idea.
8. 👍 
9. We may keep the `tabular` verbiage because some of our users leverage that snippet to build tables for visualization purposes.
10. Hm, one of our original core tenets was to ensure we create a human-readable, version control compatible project file. Is there a file type you're thinking of that would maintain that paradigm?

As I mentioned before, we really value the feedback!

**Comment by kuraga** [comment]
5. `.name`, `.description`, ... are the examples already. I just want more :)
9. I proposed to mention (i.e. _add_ the information only) the `.to_dict` method.
10. I'm thinking about databases. But yes, it may be an overhead feature.

@ak-gupta , thanks!

**Comment by ak-gupta** [comment]
Oh interesting. Happy to learn more about properties you would find helpful. In terms of database integration, we're all ears on new features but we're unlikely to prioritize it ourselves in the near future

**Comment by kuraga** [comment]
@ak-gupta , what about p. 5?

**Comment by ak-gupta** [comment]
We'd love to know what other types of properties you'd find useful! I'm hesitant to add another `Dict[str, Any]` field since I'm not sure what the distinction is between `parameters` and `properties` in this case

**Comment by kuraga** [comment]
**The first example:** there are _tests_ (and, keep in mind, _experiments_) of different _types_ on the task. A test of each _type_ has different set of metrics, etc. The test's `.type` is neither a metric nor a parameter but a _metadata_. Exactly the same, the test's `.name` and `.description` are such _metadata_.

**The second example (continuation of the first) (already coded):** during the network training, I have different tests.

Firstly, they are different types (see above): multiple tests _during_ the epoch, and more full validation _after_ the epoch. These types of tests have different _set_ of metrics, it would be conveniently to be able to _filter_ each of them. Now I'm filtering using the `.description` or available metric names.

Secondly, each test in these scheme has a real _metadata_: _number of epoch_ it was evaluated at. The `.epoch` is neither a metric nor a parameter but a _metadata_. Now I'm storing it in the `.description`, too.

**Reminder** that it's not something new: we already have the _metadata_: `.name`, `.description`.

P.S.

> I'm not sure what the distinction is between `parameters` and `properties` in this case

Tests don't have `parameters`.

**Comment by ak-gupta** [comment]
Ah ok. That makes sense. Thanks for the explanation! We were considering adding something like `tags: List[str]` which could be part of the `Experiment` and `Test` schema, along with a `filter` method on the `Project` so it's easy to get a reduced list. Do you think that would meet your requirements?

**Comment by kuraga** [comment]
Well I proposed a wider concept: _metadata_/_properties_, i.e. `Dict[str, any]` in the constructor and/or `.set_metadata(str, any)` method. And IMHO filtering methods are not mandatory: that's a user deal. Thanks!

**Comment by ak-gupta** [comment]
I'll confer with the rest of the dev team to figure out which direction we want to go. Thanks again for the input!

**Comment by kuraga** [comment]
For p.2, #31.

**Comment by kuraga** [comment]
> 9. Add the `.to_dict()` description to the Represent the project as a table tutorial (and rename the latter).

Aha, my fault. `.to_tabular` already returns list of dicts (and the how-to does mention it).

p.9 is canceled.

**Comment by kuraga** [comment]
11.

```bash
$ pytest
```
```
<...>
============================================================================================================= warnings summary ==============================================================================================================
lazyscribe/test.py:8
  /home/sasha/lazyscribe/lazyscribe/test.py:8: PytestCollectionWarning: cannot collect test class 'Test' because it has a __init__ constructor (from: tests/test_experiment.py)
    @define

lazyscribe/test.py:8
  /home/sasha/lazyscribe/lazyscribe/test.py:8: PytestCollectionWarning: cannot collect test class 'Test' because it has a __init__ constructor (from: tests/test_project.py)
    @define
```

**Comment by kuraga** [comment]
p. 6.
My opinion is: left `__repr__` unchanged, `__str__` should be `<lazyscribe.experiment.ReadOnlyExperiment object at 0x7fe57341b560>`.
I thought we could use `str=False` calling `attrs.define`/`attrs.frozen`.
But [default `__str__` implementation](https://docs.python.org/3/reference/datamodel.html#object.__str__) calls `__repr__`.
So, propose `str=False, repr=False` and `def __str__(self): return str(super(object, self))`.

p. 9.
Aha, my fault. `.to_tabular` already returns list of dicts (and the how-to does mention it).
p.9 is canceled.

p. 11.
```bash
$ pytest
```
```
<...>
============================================================================================================= warnings summary ==============================================================================================================
lazyscribe/test.py:8
  /home/sasha/lazyscribe/lazyscribe/test.py:8: PytestCollectionWarning: cannot collect test class 'Test' because it has a __init__ constructor (from: tests/test_experiment.py)
    @define

lazyscribe/test.py:8
  /home/sasha/lazyscribe/lazyscribe/test.py:8: PytestCollectionWarning: cannot collect test class 'Test' because it has a __init__ constructor (from: tests/test_project.py)
    @define
```
https://stackoverflow.com/a/72465142/556958 ?


p. 12.
Are there tests for the `Test` class?

**Comment by kuraga** [comment]
p. 13.
Propose to _not_ sort (JSON) keys on saving. It's not needed but introduces some differences...

**Comment by ak-gupta** [comment]
p. 6.

Sure, to be honest I haven't put a _ton_ of thought into the repr/str

p. 11./p. 12.

Yep, we have tests for that class; I think `pytest` is interpreting `lazyscribe.test.Test` as a test class, when it's part of the package itself -- our [code coverage](https://app.codecov.io/github/lazyscribe/lazyscribe/blob/main/lazyscribe%2Ftest.py) reports indicate that we are effectively calling it. Our testing is [somewhat minimal](https://github.com/lazyscribe/lazyscribe/blob/0b35708c3230cb84b12069557511a382131a27c3/tests/test_experiment.py#L32-L37), but the class is on the lighter side.

p. 13.

Interesting. What sort of differences? We sorted to ensure consistency, but admittedly didn't put a lot of thought into it.

**Comment by kuraga** [comment]
p. 11.

> Yep, we have tests for that class; I think `pytest` is interpreting `lazyscribe.test.Test` as a test class

https://stackoverflow.com/a/72465142/556958 suggests to put `__test__ = False` in the class definition. (I'd add a comment also.)

p. 12.

Ok, closed.

p. 13.

> We sorted to ensure consistency.

Ok, cancelled.

**Comment by kuraga** [comment]
p. 14.

In my code `created_at` and `updated_at` JSON fields are equal. Meanwhile, `created_at` is _not_ correct and `updated_at` is correct.

p. 15.

Also propose to introduce the `.touch()` method(s) which update the own `updated_at` field and the parents' ones.

**Comment by kuraga** [comment]
For p.11, see ~#33~ #34.

**Comment by kuraga** [comment]
p. 16.

`Project.merge` doesn't control the project's `mode` (while `Project.append` does).

p. 17.

`Experiment` is `@attrs.define`d.
`Test` is `@attrs.define`d.
`Project` is not.

**Comment by ak-gupta** [comment]
For p. 14 and p. 15, can you give some more detail on the bug you're seeing?

p. 16 -- are you referring to the ability to `merge` with `mode="r"` while you can't `append`?

p. 17 -- many of the [features of `attrs`](https://www.attrs.org/en/stable/why.html#hand-written-classes) against standard classes don't apply to `Project`. Our primary motivation for using it at the experiment/test level is the easy factory initialization and serialization to JSON-compatible data.

**Comment by kuraga** [comment]
p. 14, p.15.

~Opened #35.~ Ah, it's the `experiment`'s `.created_at`. So, everything is correct.
Closed.

p. 16.

Yes.

p. 17.

Ok, closed.

**Comment by ak-gupta** [comment]
p. 16.

That makes sense. Maybe we either create a wholly new project object (preserving any existing read-only project classes) or throw a similar error to the append. Any opinions on that?

**Comment by kuraga** [comment]
p. 16.

On other hand, `Project.merge` creates a _new_ project (i.e. doesn't mutate).
So, it's correct.

**Comment by kuraga** [comment]
For p. 7, see #36.

**Comment by kuraga** [comment]
p. 18.

IMHO https://github.com/lazyscribe/lazyscribe/blob/9c110cc32a24ecbf9ac5a836c2617dba253def90/lazyscribe/project.py#L334-L338 should be prefixed with `experiment_`.

**Comment by kuraga** [comment]
Also, there is an uncommented one from https://github.com/lazyscribe/lazyscribe/issues/28#issuecomment-1930681434:

> p. 8.
> 
> Maybe we may mention in the tutorials that `.experiments` and `.tests` are just plain `List`s hence `.append`ing: a) saves the order, b) saves the link instead of a copy (hence we can modify the experiment/test until `project.save()`).
> 
> UPD: We need the `Project.remove` since we have the `Project.append`. Also we should understand (and document it) that the project's `mode` is checked on the `.append` call only.

**Comment by kuraga** [comment]
p. 18.

IMHO https://github.com/lazyscribe/lazyscribe/blob/9c110cc32a24ecbf9ac5a836c2617dba253def90/lazyscribe/project.py#L334-L338 should be prefixed with `experiment_`.

The reply from @ak-gupta :

> Ah I see, yep. Instead of the user potentially interpreting those values as the "test name", experiment_name is more explicit.

p. 19.

All tutorials states `project = Project()`. Is it a good idea to not mention arguments there? Neither fpath`, nor `mode`...

**Comment by kuraga** [comment]
p. 20.

Notes on the attributes.

`Project`:

* p. 20.a. `mode: str = "w"    # could be Literal[...]`.
* p. 20.b. Also, an exception should be raised on invalid `mode`

`Experiment`:

* p. 20.c. `project: Path = field(eq=False)    # Project?`
* p. 20.d. `tests: List = Factory(lambda: [])    # List[Union[Test, ReadOnlyTest]]`

`Test`:

* p. 20.e. Add link to the parent `experiment`?

**Comment by kuraga** [comment]
> p. 1.
> 
> Yes, we've been considering a move to building our docs using GitHub Actions instead of readthedocs because we weren't able to get `sphinx-apidoc` to work with that hook -- we should expedite that.

Seems like it (module reference) should be [a little bit manual](https://github.com/joblib/joblib/blob/master/doc/index.rst).

Also, continued on the GitHub-Actions-generated-documentation at https://github.com/lazyscribe/lazyscribe/pull/29#issuecomment-2002060444.

**Comment by kuraga** [comment]
On the Artifacts.

p. 21.

`AttributeError: "numpy.ndarray" object has no attribute "__module__"`
https://github.com/lazyscribe/lazyscribe/pull/20/files#r1527474732

p. 22.

IMHO we should mention (in the documentation) the [`joblib` package](https://pypi.org/project/joblib/) as a required dependency while `handler="joblib"`.

**Comment by kuraga** [comment]
@ak-gupta , ping on p.19 and below :)

**Comment by ak-gupta** [comment]
Hey @kuraga, sorry a few of us have been on vacation the past few days. We'll be more responsive in the coming weeks! Thanks for the patience.

**Comment by kuraga** [comment]
@ak-gupta , gentle ping :)

**Comment by ak-gupta** [comment]
> p. 20.
> 
> Notes on the attributes.
> 
> `Project`:
> 
>     * p. 20.a. `mode: str = "w"    # could be Literal[...]`.
> 
>     * p. 20.b. Also, an exception should be raised on invalid `mode`.

Above resolved by #38 I believe.

> `Experiment`:
> 
>     * p. 20.c. `project: Path = field(eq=False)    # Project?`.
>       UPD: Hm.. Seems like it is a `Path`...
>       Don't we want to have the parent `Project` reference? (The `Path` is available there.)

Ideally, we want to isolate the experiment classes so they aren't aware of the `Project` at all. IMO, the Project should be aware of experiments, not the other way around. We only have a reference to the path of the project for artifact handling purposes.

>     * p. 20.d. `tests: List = Factory(lambda: [])    # List[Union[Test, ReadOnlyTest]]`.

Fixed by #38

> `Test`:
> 
>     * p. 20.e. Add the reference to the parent `experiment`?
>       See also p. 20.c.

Similar to above. Ideally, the experiment is aware of the test without the test being aware of the experiment

**Comment by ak-gupta** [comment]
> On the Artifacts.
> 
> p. 21.
> 
> `AttributeError: "numpy.ndarray" object has no attribute "__module__"` https://github.com/lazyscribe/lazyscribe/pull/20/files#r1527474732

I've added some error handling in #41 -- let me know what you think.

> p. 22.
> 
> IMHO we should mention (in the documentation) the [`joblib` package](https://pypi.org/project/joblib/) as a required dependency while `handler="joblib"`.

We have it listed in the "Additional requirements" column [here](https://lazyscribe.github.io/lazyscribe/how-to/artifact.html#id2)

**Comment by kuraga** [comment]
_p. 20.a._, _p. 20.b._, _p. 20.d._

(Will be) Closed by #38, thanks!

_p. 20.c._, _p. 20.e._

Understood. Closed.

_p. 21._

(Will be) Closed by #41, thanks!

_p. 22._

See #42.

**Comment by kuraga** [comment]
@ak-gupta , thanks very much!
Will open separate issues on enhancement requests are left.
And will point them here. And will close this issue :)

**Comment by kuraga** [comment]
_p. 4._

Closed by #38, thanks!

_p. 6._

Moved to #44.

_p. 18._

(Will be) Closed by #41, thanks!

_p. 19._

Not decided.
The [basics how-to](https://github.com/lazyscribe/lazyscribe/blob/main/docs/how-to/basic.rst) states `project = Project()`. Is it a good idea to mention arguments explicity there?
/cc @ak-gupta

**Comment by kuraga** [comment]
@ak-gupta , what do you think about p. 19?

The [basics how-to](https://github.com/lazyscribe/lazyscribe/blob/main/docs/how-to/basic.rst) states `project = Project()`. Is it a good idea to mention arguments explicity there?

**Comment by kuraga** [comment]
For p. 19, see #46.

**Comment by kuraga** [comment]
So,

* #37,
* #44.

Closing.

**Comment by kuraga** [comment]
_p. 23._

https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/lazyscribe/project.py#L390

1. Is it intended?
2. Is it required?
3. It isn't documented.

/cc @ak-gupta

**Comment by kuraga** [comment]
@ak-gupta , thanks for the reply!
Could we introduce a `to_tabular`'s parameter for this?

**Comment by kuraga** [comment]
_p. 24._

There is a `pytest` warning:
```
============================================================================================================= warnings summary ==============================================================================================================
tests/conftest.py:9
  /home/sasha/lazyscribe/tests/conftest.py:9: PytestCollectionWarning: cannot collect test class 'TestArtifact' because it has a __init__ constructor (from: tests/test_project.py)
    class TestArtifact(Artifact):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

_p. 25._

What is the [`Project.merge`]'s (https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/lazyscribe/project.py#L213) "replacement policy"? Is it [here](https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/lazyscribe/project.py#L229)? Don't see the answer from the [test](https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/tests/data/project.json) [data](https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/tests/data/merge_append.json)...

**Comment by ak-gupta** [comment]
It's mostly defined [here](https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/lazyscribe/linked.py#L88), with binary comparisons defined [here](https://github.com/lazyscribe/lazyscribe/blob/129641f82430a52882995bf4765efa27771598db/lazyscribe/experiment.py#L402-L442). Docs on the process are [here](https://lazyscribe.github.io/lazyscribe/how-to/merge.html).

**Comment by kuraga** [comment]
_p. 24._

> Docs on the process are [here](https://lazyscribe.github.io/lazyscribe/how-to/merge.html).

Let's copy the  formal part to the `Project..merge` and `Project.append` methods' docs?

_p. 23._

Look at https://github.com/lazyscribe/lazyscribe/issues/28#issuecomment-2315605345, please.

**Comment by kuraga** [comment]
@ak-gupta , gentle ping on the lat comment, other issues and PRs :)

**Comment by kuraga** [comment]
@ak-gupta , gentle ping on the last comment, other issues and PRs :)

**Comment by ak-gupta** [comment]
Hey @kuraga, sorry for the delay. Looking at some things now.

**Comment by kuraga** [comment]
@ak-gupta , thanks so much!

_p. 24._

It's going to be fixed by https://github.com/lazyscribe/lazyscribe/commit/04d71f47b5e7d8ed05f5fb50ebf19f0197d103ba.

**Comment by kuraga** [comment]
_p. 25._

Partially fixed by https://github.com/lazyscribe/lazyscribe/commit/04d71f47b5e7d8ed05f5fb50ebf19f0197d103ba.
Let's do similar for `Project.append`?

**Comment by kuraga** [comment]
All solved.
