### ISSUE TITLE
[Proposition]  Metadata for experiments and tests

### ISSUE THREAD

**Issue by kuraga** [lazyscribe/lazyscribe#44]
Continuation of #28 , p. 6.

**Idea:** to introduce _metadata_ (string-keyed any-valued dictionary) for _experiments_ and _tests_.

1. The `Experiment`'s constructor should have the `metadata: dict[str, any]` argument.
It is stored in the object, say `experiment`.
2. There is the `experiment.metadata` attribute.
3. There is a way to mutate `.metadata`.
Maybe, the `experiment.add_metadata(name: str, value: any)` method.
4. The same for `Test`s.
5. Integrate the `.name`, `.description`, etc. into the `.metadata`?

---

Reminder that it's not something new: we already have the metadata, `.name` and `.description`.

---

> What is the distinction is between `parameters` and `metadata` in this case?

1. Tests don't have `parameters`.
2. See "The second example" -> "Secondly, ...".

---

**The first example:** there are _tests_ (and, keep in mind, _experiments_) of different _types_ on the task. A test of each _type_ has different set of metrics, etc. The test's `.type` is neither a metric nor a parameter but a _metadata_. Exactly the same, the test's `.name` and `.description` are such _metadata_.

---

**The second example (continuation of the first):** during the network training, I have different tests.

Firstly, they are different types (see above): multiple tests _during_ the epoch, and more full validation _after_ the epoch. These types of tests have different _set_ of metrics, it would be conveniently to be able to _filter_ each of them. Now I'm filtering using the `.description` or available metric names.

Secondly, each test in these scheme has a real _metadata_: _number of epoch_ it was evaluated at. The `.epoch` is neither a metric nor a parameter but a _metadata_. Now I'm storing it in the `.description`, too.

---

#43 adds kind of such _metadata_: the _tags_ for experiments: `experiment.tags: list[str]`.

**Comment by ak-gupta** [comment]
Hm, we view all of `lazyscribe` as metadata collection, with the added explicit fields for inputs (`parameters`) and outputs (`artifacts`, `metrics`). We're a bit wary of either collapsing all of the fields down to a `metadata` key or adding another dictionary. I think it has the potential to confuse users (e.g. "should I log this as metadata? Or a parameter?").

We can add `parameters` to the `Test` object, but other than that we're more focused on specific additional metadata logging (`tags` being an example).

**Comment by kuraga** [comment]
> I think it has the potential to confuse users (e.g. "should I log this as metadata? Or a parameter?").

Makes sense.

> We can add `parameters` to the `Test` object

Agree. Will I take?

**Comment by kuraga** [comment]
@ak-gupta , will I take or is there some architecture considerations? :)

**Comment by ak-gupta** [comment]
Hey @kuraga, sorry I didn't respond earlier. If you'd like to take on adding `parameters` to the `Test` object I'm all for it. Thanks again!

**Comment by kuraga** [comment]
Implemented in #60.

**Comment by kuraga** [comment]
Done.
